#!/usr/bin/env zsh

NUM_DISPLAYS=$(system_profiler SPDisplaysDataType | grep -c 'Resolution')

FONT_FACE="JetBrainsMono Nerd Font"

PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
    height=47 \
    color=0x00000000 \
    margin=0 \
    sticky=on \
    padding_left=15 \
    padding_right=15 \
    notch_width=220 \
    display=all

    # label.color=0xffcad3f5 \
    # background.color=0x66494d64 \
sketchybar --default \
    background.color=0x9924273a \
    background.corner_radius=5 \
    background.padding_right=5 \
    background.padding_left=5 \
    background.height=29 \
    icon.font="$FONT_FACE:Medium:15.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.font="$FONT_FACE:Bold:14.0" \
    label.color=0xffffffff \
    label.y_offset=0 \
    label.padding_left=0 \
    label.padding_right=5 \

sketchybar --add item current_space left \
    --set current_space \
    background.color=0xffa6da95 \
    icon.color=0xff24273a \
    label.drawing=off \
    script="$PLUGIN_SHARED_DIR/current_space.sh" \
    --subscribe current_space space_change mouse.clicked

# Show AeroSpace workspaces in Sketchybar
sketchybar --add event aerospace_workspace_change

for mid in $(aerospace list-monitors --format %{monitor-id}); do
  for sid in $(aerospace list-workspaces --monitor $mid | tac); do
    sketchybar --add item space.$mid.$sid q \
        --subscribe space.$mid.$sid aerospace_workspace_change space_windows_change\
        --set space.$mid.$sid \
        background.padding_right=0 \
        background.padding_left=0 \
        background.corner_radius=5 \
        background.color=0xfff5a97f \
        background.drawing=off \
        label=$sid \
        label.drawing=no \
        label.font="$FONT_FACE:Bold:15.0" \
        label.padding_left=-4 \
        label.padding_right=8 \
        icon.drawing=off \
        click_script="aerospace workspace $sid" \
        script="$CONFIG_DIR/plugins/aerospace.sh $mid $sid" \
        display=$mid
  done
  sketchybar --add bracket space_bracket_$mid "/space\\.${mid}\\..*/" \
      --set space_bracket_$mid disply=$mid
done

sketchybar --add item front_app e \
    --set front_app \
    background.color=0xffa6da95 \
    background.padding_left=0 \
    icon.color=0xff24273a \
    label.drawing=no \
    script="$PLUGIN_SHARED_DIR/front_app.sh" \
    --add item front_app.name e \
    --set front_app.name \
    background.padding_left=-5 \
    background.drawing=off \
    label.font="$FONT_FACE:Bold:14.0" \
    label.padding_left=-2 \

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.name \
    --subscribe front_app front_app_switched

sketchybar --add item weather left \
    --set weather \
    icon= \
    icon.color=0xfff5bde6 \
    icon.font="$FONT_FACE:Bold:15.0" \
    icon.padding_left=8 \
    update_freq=600 \
    script="$PLUGIN_SHARED_DIR/weather.sh" \
    label.font="$FONT_FACE:Bold:14.0" \
    label.padding_right=8 \
    --subscribe weather system_woke

sketchybar --add event spotify_change $SPOTIFY_EVENT \
    --add item spotify left \
    --set spotify \
    icon= \
    icon.padding_left=7 \
    icon.font="$FONT_FACE:Bold:20.0" \
    label.drawing=off \
    label.padding_left=3 \
    script="$PLUGIN_SHARED_DIR/spotify.sh" \
    --subscribe spotify spotify_change mouse.clicked

sketchybar --add item weather.moon right \
    --set weather.moon \
    icon.color=0xfff3b817\
    icon.font="$FONT_FACE:Bold:22.0" \
    icon.padding_left=6 \
    icon.padding_right=4 \
    label.drawing=off \
    --subscribe weather.moon mouse.clicked

sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    icon.color=0xffed8796 \
    icon.padding_left=8 \
    update_freq=10 \
    script="$PLUGIN_SHARED_DIR/clock.sh" \
    label.font="$FONT_FACE:Bold:14.0" \
    label.padding_right=8

sketchybar --add item battery ri3ht \
    --set battery \
    update_freq=20 \
    icon.padding_left=8 \
    script="$PLUGIN_SHARED_DIR/battery.sh" \
    label.font="$FONT_FACE:Bold:14.0" \
    label.padding_right=8

sketchybar --add item volume right \
    --set volume \
    icon.color=0xff8aadf4 \
    label.drawing=true \
    icon.padding_left=8 \
    script="$PLUGIN_SHARED_DIR/volume.sh" \
    --subscribe volume volume_change \
    label.font="$FONT_FACE:Bold:14.0" \
    label.padding_right=8

# osascript -e 'quit app "Rectangle"'
# open -a Rectangle

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
